import Navbar from "@/components/Navbar";
import ContactSection from "@/components/sections/ContactSection";

import HeaderSection from "@/components/sections/HeaderSection";
import RemindSection from "@/components/sections/RemindSection";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-x-hidden text-white font-customSans">
        <Navbar />
        <HeaderSection />
        <main>

          <RemindSection />
        </main>
        <ContactSection />
      </div>
    </>
  );
}
